### ISSUE TITLE
Dicom loading example broken

### ISSUE THREAD

**Issue by kofifus** [chafey/cornerstone#113]
the example at https://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html seems to be broken

When loading an image I get `cornerstoneWADOImageLoader is not defined`

thx!

**Comment by swederik** [comment]
Whoops, this was broken by a recent update to the build process towards ES6 support. This has been fixed now by https://github.com/chafey/cornerstoneWADOImageLoader/pull/82.

Thanks for the report!
