### ISSUE TITLE
Gray scale values not inverted in 0.10.8

### ISSUE THREAD

**Issue by jialeigary** [chafey/cornerstone#115]
Hi,
    When I load DICOM images with Tag "0028,0004  Photometric Interpretation: MONOCHROME1" in 0.10.8, the gray scale values are not inverted. But in 0.10.7, it works very well. The attachment is the reproducing code with a test DICOM file.  Please add a link named "js" at the folder root to any folder in vault for version switch. 

[Attachment](https://drive.google.com/file/d/0ByvdwgscZoU2RGYxOWpsMUREWms/view?usp=sharing)

Thanks,
Gary

**Comment by swederik** [comment]
Oh, that's not good.... Thanks for the report!

**Comment by swederik** [comment]
Looks like this was introduced here:

https://github.com/chafey/cornerstone/commit/484ab38244438cb75a3c536149160d0284d823a7#diff-d2bf464b9c95f00c8901c4df44ecbaf1R89

It should be fixed now.
