### ISSUE TITLE
Cornerstone demo does not display images

### ISSUE THREAD

**Issue by adizhol** [chafey/cornerstone#116]
In http://chafey.github.io/cornerstoneDemo/
Using Chrome
Console shows the following exception
```
Uncaught dicomParser.parseDicom: DICM prefix not found at location 132
readPrefix @ dicomParser.js:57
readPart10Header @ dicomParser.js:65
parseTheByteStream @ dicomParser.js:162
dicomParser.parseDicom @ dicomParser.js:170
xhr.onreadystatechange @ cornerstoneWADOImageLoader.js:3749
```

**Comment by swederik** [comment]
Most likely this is because the example images have been removed from the server. The CornerstoneDemo is deprecated, you should look at http://viewer.ohif.org/ as an example instead. The code can be found here: https://github.com/OHIF/Viewers/
