### ISSUE TITLE
Push latest release to NPM

### ISSUE THREAD

**Issue by superbull** [chafey/cornerstone#118]
Hi, I found the latest version on NPM package repository is:

- cornerstone: 0.1.0
- cornerstoneWADOImageLoader: 0.5.0
- cornerstoneTools: none

Why not push the latest releases to NPM automatically?

**Comment by swederik** [comment]
Hi there,

We were hoping we could get the 'cornerstone' name, but that's not going to happen. I've now published it as 'cornerstone-core'. The rest of the libraries will be on NPM soon!
