### ISSUE TITLE
Enfore a uniform coding style

### ISSUE THREAD

**Issue by jpambrun** [chafey/cornerstone#12]
I see 

```
if (..) {
}
```

```
if (..)
{
}
```

```
}
else
}
```

```
} else {
```

It should be standardized. Maybe using a formatting tool?

**Comment by chafey** [comment]
I agree, it should be consistent.  Do you know of a tool that can help us with this?  We are already using jshint, maybe we just need to add some options?

**Comment by knopkem** [comment]
I can recommend jsbeautifier, plays nice with jsLint/Hint...

I use it like this:
<pre>
jsbeautifier: {
            files: ['Gruntfile.js', 'src/**/*.js', 'tests/**/*.js'],
            options: {
                js: {
                    jslintHappy: true
                }
            }
        },
</pre>

**Comment by chafey** [comment]
Does that overwrite/update the files automatically?

**Comment by knopkem** [comment]
Not sure to fully understand. It updates the files (given in the directories) in place, when running grunt.
Afaik there is a grunt filewatcher that runs each time you change your files, but haven't tried it.
Personally I run it just before committing.

**Comment by chafey** [comment]
If anyone wants to write up some coding guidelines + jslint files to help catch violations I would be more than happy to incorporate it into the build steps.

**Comment by swederik** [comment]
We can / should use the JSHint and JSCS settings from Cornerstone Tools:

https://github.com/chafey/cornerstoneTools/blob/master/.jscsrc
https://github.com/chafey/cornerstoneTools/blob/master/gruntfile.js#L85

We may need to use eslint once we switch to ES6 though, not sure.

**Comment by swederik** [comment]
Closing because ESLint is now part of the build process (though some of the rules have been temporarily commented out).
