### ISSUE TITLE
Trigger events on the cornerstone object fails, if the library is loaded as an AMD module

### ISSUE THREAD

**Issue by adreyfus** [chafey/cornerstone#124]
If cornerstone is used as an AMD module, the events like `$(cornerstone).trigger('CornerstoneImageCacheFull', cacheInfo);`, or `$(cornerstone).trigger('CornerstoneImageLoaded', { image: image });` fail, because the variable `cornerstone` is not defined from inside `cornerstone.js`.

**Comment by swederik** [comment]
Hi Aloïs,

We noticed this as well and are trying to fix it. I'll keep the ticket open until that's complete. Thanks for the report!

**Comment by swederik** [comment]
I have moved Events to fire on $(cornerstone.events) so that you can use this when importing as an AMD module as well.
