### ISSUE TITLE
Cornerstone displaying studies generated by GE Vivid E9

### ISSUE THREAD

**Issue by jssuttles** [chafey/cornerstone#127]
Hi Everyone,

I am working on a project to use Cornerstone to display echocardiograms —  all of the echocardiogram samples that I have found online work perfectly using Cornerstone, however, live studies coming directly off of a GE Vingmed Ultrasound Vivid E9 are not viewable using Cornerstone.

A sample study from this modality contains 2 series, one of which is an SR, and one of which has 85 multi-frame US instances. On another viewer, each of these instances are displayed as a sequence. As far as I can tell, Cornerstone hangs up on the fact that there isn’t defined image offsets.

Unfortunately, this modality writes the patient name into the DICOM image. Hence, the study cannot be properly anonymized and shared.

Any help here would be greatly appreciated. Please feel free to contact me directly if you'd like to see the sample study.

Kind Regards, 
Jason Suttles
jason@medicom.us
844-686-9599x42 (office)
919-589-2287 (cell)

**Comment by swederik** [comment]
Maybe DicomCleaner can erase the burned-in tags? http://www.dclunie.com/pixelmed/software/webstart/DicomCleanerUsage.html

**Comment by jssuttles** [comment]
DicomCleaner couldn't read the dicoms either. So, I couldn't clean them. This issue might end up being resolved on the modality end. I'll close this issue if that ends up being the case. Otherwise, I'll bring in more details to help resolve the issue.

**Comment by Revln9** [comment]
if you can point us to a link of  a vivid E9 dicom, it will be helpful

**Comment by jssuttles** [comment]
I'll just close this for now until I can figure out what's going on. It's getting a little complicated. There's something doing a weird conversion and I just have to figure out what's creating the non-standard dicom. Thanks for the help. DicomCleaner will come in handy.

**Comment by zdavatz** [comment]
Try to look at the images using Miele-LXIV: https://apps.apple.com/us/app/miele-lxiv/id988332475?mt=12 it is free and OpenSource.
