### ISSUE TITLE
WebGL performance brutally slow on Chrome 59

### ISSUE THREAD

**Issue by swederik** [chafey/cornerstone#134]
Worked fine on 58, update to 59 and all of a sudden scrolling between images is painfully slow.

<img width="1148" alt="screenshot 2017-06-15 14 33 36" src="https://user-images.githubusercontent.com/607793/27181415-d6ee91be-51d7-11e7-834b-4e857ba91b5a.png">

**Comment by inkorcoder** [comment]
same problem on Ubuntu 14.05
Chrome 59
5-14fps

**Comment by swederik** [comment]
This appears to have been caused by the parseInt issue referenced here: https://github.com/chafey/cornerstone/issues/175

I am now unable to reproduce it. Feel free to reopen this if you have this issue.
