### ISSUE TITLE
cornerstone.webGL.isWebGLInitialized allways false?

### ISSUE THREAD

**Issue by leonardorame** [chafey/cornerstone#136]
In Cornerstone  0.11.0 i'm getting `false` when I check `cornerstone.webGL.isWebGLInitialized` even if I've setup `cornerstone.enable(element, {renderer: 'webgl'})`. 

Has this changed recently?.

**Comment by swederik** [comment]
I don't think it's changed recently, but I also don't remember specifically ever testing it.
