### ISSUE TITLE
Orthanc

### ISSUE THREAD

**Issue by djones4487169** [chafey/cornerstone#138]
How would I use cornerstone to connect to a PACS server like Orthanc over the web so that everything is accessible from anywhere ? WOuld I need to set up some sort of client/server system? Any ideas appreciated.

Thanks
David

**Comment by swederik** [comment]
Hi David,

You can use the WADO Image Loader (https://github.com/chafey/cornerstoneWADOImageLoader/) to retrieve images directly from your PACS with WADO as long as you have a proxy in front of your PACS to avoid CORS errors (see https://github.com/chafey/cornerstoneWADOImageLoader/wiki/CORS).

**Comment by FMCalisto** [comment]
I am not understanding how to connect both. Can you give me some help here?

Thank you.

**Comment by dannyrb** [comment]
What have you already tried? Where are you getting hung up? By "connect both" do you mean Cornerstone and the WADOImageLoader, or the WADOImageLoader and your PACS?

**Comment by FMCalisto** [comment]
I just clone the [conerstoneWADOImageLoader](https://github.com/cornerstonejs/cornerstoneWADOImageLoader) and run it. I have no idea where to start and what to read about this lib. Being a noob I know, sorry. Just want to know the right path through it. By "connect both" I mean to connect [cornerstoneDemo](https://github.com/chafey/cornerstoneDemo) with [Orthanc](https://www.orthanc-server.com/) automatically.

**Comment by dannyrb** [comment]
To clarify, are you looking to build your own viewer? That process can be a bit more involved and requires using multiple libraries depending on the functionality you want:

_Core_
- `cornerstone-core`: 

_Image Loaders_ (How you get images into Cornerstone)
- `cornerstone-wado-image-loader` - DICOM
- `cornerstone-web-image-loader` - JPEG/PNG

_Tools_ (For advanced tool functionality + framework)
- `cornerstone-tools`

If you're looking for a viewer to point at Orthanc, then I'd recommend taking a look at [OHIF's Viewer](http://viewer.ohif.org/). You can find documentation on it [in their wiki](https://github.com/OHIF/Viewers/wiki). @swederik is our resident expert.

**Comment by FMCalisto** [comment]
Thank you for your clarification. However, we have several questions about what you just said:

1. What is the real purpose of the `cornerstone-wado-image-loader`?

2. Don't think that a `cornerstone-web-image-loader` is needed since we are using DICOM format directly. Am I right?

3. Like already said, we are using the [cornerstoneDemo](https://github.com/chafey/cornerstoneDemo). Was not suppose to have something on this system to automatically consume [Orthanc](https://www.orthanc-server.com/) images?

4. Does [OHIF's Viewer](http://viewer.ohif.org/) has an automatic mechanism to do that?

Thank you.

**Comment by dannyrb** [comment]
`cornerstone-wado-image-loader` is an implementation of an `imageLoader`. You can register many image loader's with `cornerstone-core`. Each one works as a way to pull image data into `cornerstone-core`.

`cornerstone-wado-image-loader` specifically, utilizes workers to decode DICOMs into pixelData that `cornerstone-core` can display. It also uses `dicom-parser` to pull out DICOM metadata/tags so they can be associated with the image.

If you did build your own solution, if you're only using DICOM images, you likely won't need the `cornerstone-web-image-loader`.

For a higher level analogy, all of **these libraries are car parts** that you can use to assemble your own car. Solutions like **`cornerstone Demo` and the OHIF Viewer are fully built cars** that use some of the car parts in the Cornerstone family, as well as some extra sauce/magic that make them unique.

cornerstoneDemo is _not_ maintained by this community. The OHIF Viewer has an organization backing it, and is constantly improving.

I'm not 100% sure. For OHIF related questions, you can ask in their [GitHub repository for their viewer](https://github.com/OHIF/Viewers/issues). @swederik would be a good resource, and may be able to point you toward a better place to ask questions.

**Comment by FMCalisto** [comment]
Thank you very much @dannyrb.
