### ISSUE TITLE
Anonymize DICOM files with javascript

### ISSUE THREAD

**Issue by krunalrspl** [chafey/cornerstone#139]
I'm triying to anonymize dcm (dicom) files before uploading it to the server. 

I want to do it on the client side using javascript. But I can't find more that dicom viewers.

I searched about the tags of dicom and I have found a lot of tools for remove metadata tags using python, java and ruby, but I don't know how to portrait it to javascript.

I have even decided what tags I would remove, but I'm not sure about how to do it.

Any ideas about?

Thanks for your time

**Comment by swederik** [comment]
With @pieper we have actually just started working on something for this over here: https://github.com/pieper/dcmjs

but it's very much in alpha phase at this point. I'll post here when we have a useful example.

**Comment by krunalrspl** [comment]
Thanks you so much @swederik...

**Comment by swederik** [comment]
Oh I forgot that we also have this example here as well: https://rawgit.com/chafey/dicomParser/master/examples/simpleDeIdentify/index.html
