### ISSUE TITLE
Alpha channel of getPixelData() function

### ISSUE THREAD

**Issue by tymiao1220** [chafey/cornerstone#147]
Hi,

I am using this wonderful lib to build my own web-app. I encounter some issue when doing thresholding, the problem is after I 'loadAndCacheImage(ID)' I call image.getPixelData() and set the corresponding index to be some RGB color. e.g.
        for foreground( if >thresholding):
                image.getPixelData()[i*4]=255;
                image.getPixelData()[i*4+1]=0;
                image.getPixelData()[i*4+2]=0;
                image.getPixelData()[i*4+3]=0;
        for background( if <=thresholding):
                mage.getPixelData()[i*4]=0;
                image.getPixelData()[i*4+1]=0;
                image.getPixelData()[i*4+2]=0;
                image.getPixelData()[i*4+3]=0;

RGB works prefect, but the alpha channel seems not working no matter what value I set it to be. I was doing that by setting total canvas element opacity 0.4 to overlay on the original image, but that will make background darker (because overlayed thresholding image background is back), so that why I am thinking can I just set foreground alpha to be 255 and background to be 0.

Could you give me some help! Appreciated!

**Comment by swederik** [comment]
You probably need to set image.rgba = true for it to use the alpha channel. Could you try that?
