### ISSUE TITLE
Reset / Revert Image

### ISSUE THREAD

**Issue by cancan101** [chafey/cornerstone#15]
After panning / zooming, changing WW/WC and placing annotations on the image, what should be called to revert the image to its initial state?

**Comment by chafey** [comment]
call displayImage() to reset it with an undefined viewport

**Comment by cancan101** [comment]
Is this a new feature (added in recent commits or should this be working in old code)? It does not appear to work using the older version of Cornerstone.
This works slightly better although there are still some quirks:
```js
var defViewport = cornerstone.getDefaultViewport(element, image);
cornerstone.displayImage(element, image, defViewport);
```

**Comment by tlacaelelrl** [comment]
I know this is closed but I was looking for this and ended up using 

`cornerstone.reset(element);`
