### ISSUE TITLE
Cornerstone and create-react-app

### ISSUE THREAD

**Issue by AlexandrMalusek** [chafey/cornerstone#151]
Hi,

I have a beginner's question. Is it possible to use the cornerstone libraries (cornerstone-core, cornerstone-tools, ...) in the framework created by [create-react-app](https://github.com/facebookincubator/create-react-app)? I haven't managed to get it working, but I'm not a JavaScript expert.

Regards,
Alexandr

**Comment by medihack** [comment]
I didn't get it working either. But I am working on a solution. Currently, I am removing all the global jQuery stuff from all Cornerstone libraries.

**Comment by dannyrb** [comment]
I've created react and vue related apps that incorporated cornerstone. From what I can tell, `create-react-app` does not appear to impose any restrictions that would prevent you from using the cornerstone library/family.

If you experience issues, or have specific questions, let me know and I will try to answer them. Closing this for now. Updating to question, not bug.
