### ISSUE TITLE
It seems that the optional max/min value (00280106/00280107)tags can't be used to calculate the look up table 's length. 

### ISSUE THREAD

**Issue by OrNot** [chafey/cornerstone#162]
if (image.cachedLut === undefined) {
    const length = image.maxPixelValue - Math.min(image.minPixelValue, 0) + 1;

    image.cachedLut = {};
    image.cachedLut.lutArray = new Uint8ClampedArray(length);
  }

The length variable may not be set correctly if the tags (00280106/00280107) doesn't exist in the dicom header.  The image won't be shown somehow.

**Comment by swederik** [comment]
Normally we calculate those values if they are not present, but there was a bug in WADO Image Loader which was preventing this recently. There should be a console error if they are incorrectly set.

See https://github.com/chafey/cornerstoneWADOImageLoader/blob/f25df0a2fafa6f132cd04be15230b97857cd2419/src/webWorker/decodeTask/decodeTask.js#L48

**Comment by OrNot** [comment]
Thanks a  lot
