### ISSUE TITLE
how to clear canvas？

### ISSUE THREAD

**Issue by chaoranfeng** [chafey/cornerstone#163]
I have finished drawing the div on the div and now i want to clear the canvas and how do i clear it? You can get to the automatically generated canvas, but can not do some operation

**Comment by swederik** [comment]
I do not understand the question. You want to remove the image? cornerstone.disable(element) ?

**Comment by swederik** [comment]
https://www.w3schools.com/tags/canvas_clearrect.asp

**Comment by govi20** [comment]
cornerstone.disable(element); what is the element? is it canvas?

**Comment by dannyrb** [comment]
@govi20 

```
var myElement = $("#cornerstone-element")

// How you create a new "enabledElement"
cornerstone.enable(myElement)

// The opposite of enable
cornerstone.disable(myElement)
```

Sent from my phone. I'll circle back to clean up this answer if it's wrong or needs some love later.

**Comment by arodriguezsinergyz** [comment]
tengo este componetne simple

import { Component, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import * as cornerstone from 'cornerstone-core';
import * as cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader';
import * as dicomParser from 'dicom-parser';

@Component({
  selector: 'app-simple',
  imports: [],
  templateUrl: './simple.component.html',
  styleUrl: './simple.component.scss',
})
export class SimpleComponent implements AfterViewInit {
  @ViewChild('canvas') canvasRef!: ElementRef<HTMLCanvasElement>;
  canvas!: HTMLCanvasElement;
  element: any;

  ngAfterViewInit() {
    if (this.canvasRef) {
      this.canvas = this.canvasRef.nativeElement;
      cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
      cornerstoneWADOImageLoader.external.dicomParser = dicomParser;
      cornerstone.enable(this.canvas);
      this.loadImage();
    } else {
      console.error('Canvas no está disponible en ngAfterViewInit.');
    }
  }

  loadImage() {
    const imageId = `wadouri:/img/dicon.dcm`;
    console.log('Cargando imagen desde:', imageId);

    cornerstone
      .loadImage(imageId)
      .then((image: any) => {
        cornerstone.displayImage(this.canvas, image);
        cornerstone.fitToWindow(this.canvas);
      })
      .catch((error: any) => {
        console.error('Error al cargar la imagen DICOM:', error);
      });
  }
}

// y no me muestra nada, pero no da error

**Comment by No-Dream-No-Life** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，邮件我已收到，我将在看到后第一时间给您回复。
