### ISSUE TITLE
remove a drawn shape (line, angle, etc)

### ISSUE THREAD

**Issue by ra00l** [chafey/cornerstone#17]
I'm trying to figure out if you have support for deleting a shape, couldn't find any code to do that. Thought I'd ask before going further, so: is there any way to remove the shape? Or do we have to implement that ourselves?

Thanks for a GREAT library!

**Comment by chafey** [comment]
Yes, someone just contributed a feature to cornerstoneTools to remove tool data - check that out

**Comment by ra00l** [comment]
That was me :) Thanks for accepting my code. More will come in a couple of days...

**Comment by chafey** [comment]
Ahh OK thanks again for the contribution!  I have been so crazy busy
recently that I haven't had time to review everything so I delegated to
@swederik to help me out.  Glad you find cornerstone useful and I look
forward to more contributions!
