### ISSUE TITLE
parseInt in storedPixelDataToImageData

### ISSUE THREAD

**Issue by freund17** [chafey/cornerstone#175]
The WebGL Shaders (in `cornerstone/src/webgl/shaders/`) all use parseInt to convert the values of `pixelData` (already integer type as far as I know) to - well - integers.

This is a very expensive and - in my mind - unnecessary operation.
Is there a good reason behind it?

Keeping in mind that bitwise-operations - as used in, for example, https://github.com/chafey/cornerstone/blob/master/src/webgl/shaders/int16.js line 27/28 - implicitly convert numbers to integers.

**Comment by jpambrun** [comment]
Doesn't make much sense indeed. Did I write that?!

**Comment by swederik** [comment]
Fixed in #175 by @ayselafsar. Thanks for the report!
