### ISSUE TITLE
Importing images

### ISSUE THREAD

**Issue by ManuelTinoco** [chafey/cornerstone#21]
I can't found from where is cornerstone charging the images.
Where is the reference to the database? I want to modify to be capable of import images from the local pc.

**Comment by lolo18610** [comment]
So, from where is the cornerstone importing the studies to show?

**Comment by chafey** [comment]
Cornerstone is a client side library only and depends on an Image Loader to communicate with a server to get the image data.  There are several image loaders available including one that works with WADO-URI.  Please post follow-up questions on the cornerstone forum so others can benefit from the answer!

**Comment by lolo18610** [comment]
So,  where is cornerstone establishing communication with WADO Server?

**Comment by chafey** [comment]
https://github.com/chafey/cornerstoneWADOImageLoader
