### ISSUE TITLE
cornerstone + dicomParser to display image from DCM file

### ISSUE THREAD

**Issue by sebastiankozub** [chafey/cornerstone#24]
I'd like to use the JS libraries (cornerstone + dicomParser) together to
load and display DCM file on the website. I use AJAX to get DCM file as base64 string. Then I'd like to use dicomParser to get image base64 string from DCM base64 file to use it with cornerstone... but I can't get it. Could anyone help me?

**Comment by NicolasRannou** [comment]
any reason you are not using an array buffer to get the DCM file through AJAX?

```
   // fetch the data!
      var oReq = new XMLHttpRequest();
      oReq.open('GET', url, true);
      oReq.responseType = 'arraybuffer';
      
      oReq.onload = function(oEvent) {
        var arrayBuffer = oReq.response;
        if (arrayBuffer) {
          parser = new vjsParsersDicom(arrayBuffer, 0);
        }
      };
      oReq.send();
```

**Comment by sebastiankozub** [comment]
My problem was asynchronous character of $.ajax() calling. That's why I could see an image, but black screen. Thanks for the help... your code helped to remind of that ;)

**Comment by chafey** [comment]
All network communication is asynchronous in the browser, your black images have nothing to do with that.  $.ajax() currently does not support the responseType property so you cannot request the data be returned to you as an arraybuffer - that is probably why you are getting the black images.  You can use XHR (as Nicolas suggested) or perhaps an ajax transport to add this capability if you must use $.ajax:

http://www.henryalgus.com/reading-binary-files-using-jquery-ajax/

Note that all of this is already taken care of for you by the cornerstoneWADOImageLoader here:

https://github.com/chafey/cornerstoneWADOImageLoader

Is there a reason you don't want to use it?

**Comment by sebastiankozub** [comment]
I don't know WADO technology. My serwer serves DCM file as base64 string. 

Now (see code below) dicomParser works OK. It parses everything I like and correctly but I can't get pixelDataAsString (undefined whole time) from it to display image. `globalDCM` is variable where base64 DCM file is kept after AJAX finish
Moreover when I uncomment `return getPixelData1(globalDCM);` line and comment line before I get image but destroyed a little bit (header bytes are still present in image bytes?). How can I parse pixelData from DataSet to the format accepted by `cornerstone`.

```javascript
    function getExampleImage(imageId) {

        function getPixelData2()
        {
                var arrayBuffer = base64ToArrayBuffer(globalDCM);
                var byteArray = new Uint8Array(arrayBuffer);
                var dicomDataSet = dicomParser.parseDicom(byteArray);
                var pixelData = dicomDataSet.elements.x7fe00010;
                var pixelDataAsString = dicomDataSet.pixelDataAsString;
                return str2ab(pixelDataAsString);
                //return getPixelData(globalDCM);
        }

        var arrayBuffer = base64ToArrayBuffer(globalDCM);
        var byteArray = new Uint8Array(arrayBuffer);
        var dicomDataSet = dicomParser.parseDicom(byteArray);

        var rows = dicomDataSet.uint16('x00280010');
        var cols = dicomDataSet.uint16('x00280011');

        var windowCenter = dicomDataSet.floatString('x00281050');
        var windowWidth = dicomDataSet.floatString('x00281051');

        var minPixelValue = dicomDataSet.uint16('x00280106');
        var maxPixelValue = dicomDataSet.uint16('x00280107');

        var image = {
            imageId: imageId,
            minPixelValue: minPixelValue,
            maxPixelValue: maxPixelValue,
            slope: 1.0,
            intercept: 0,
            windowCenter: windowCenter,
            windowWidth: windowWidth,
            render: cornerstone.renderGrayscaleImage,
            getPixelData: getPixelData2,
            rows: rows,
            columns: cols,
            height: rows,
            width: cols,
            color: false,
            columnPixelSpacing: 1.09375,
            rowPixelSpacing: 1.09375,
            sizeInBytes: rows * cols * 2
        };

        var deferred = $.Deferred();
        deferred.resolve(image);
        return deferred;
    }

```

**Comment by chafey** [comment]
If you can serve DICOM P10 via HTTP get you can use cornerstoneWADOImageLoader.  You don't need a full WADO implementation nor does the URI path need to conform to WADO.  You can even use a generic web server like IIS, Apache or Nginx for this - simply put some DICOM P10 files in a folder that a web server serves up (this is exactly how the cornerstoneDemo works - I am using Apache).  You can also serve up DICOM P10 by writing an HTTP GET handler in whatever technology you are using on the server side.  Since your server is already serving up DICOM P10 base 64 encoded, I am hoping you can just remove the base64 encoding and just use cornerstoneWADOImageLoader.  Is it possible for you to use the WADO approach or are you unable to change the server side?  If you must stick with base64 encoded images, you should build your image loader off of the cornerstoneWADOImageLoader and simply do the base 64 decoding at the right spot.  There is a lot to writing an image loader and you should use an existing one unless you have a very good reason not to

**Comment by sebastiankozub** [comment]
I have changed my server to push out clear DCM file:
```javascript
        public FileResult GetByteArray(string sopInstId)
        {
            byte[] arr2 = System.IO.File.ReadAllBytes("C:\\formedicus\\data\\12345678c\\1.3.6.1.4.1.25403.127846692655492.6004.20150703091003.2_0004_000003_14361897730253.dcm");
            var str = MimeMapping.GetMimeMapping("C:\\formedicus\\data\\12345678c\\1.3.6.1.4.1.25403.127846692655492.6004.20150703091003.2_0004_000003_14361897730253.dcm");
            return File(arr2, MimeMapping.GetMimeMapping("C:\\formedicus\\data\\12345678c\\1.3.6.1.4.1.25403.127846692655492.6004.20150703091003.2_0004_000003_14361897730253.dcm"), "file.dcm");
        }
```
But now it does not work even with your example that I get here https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/examples/index.html

File is downloading when I use REST client. File is ok, I can see it in ClearCanvas...
What is P10... It's the first time I heard about P10? Maybe my studies are corrupted?

**Comment by chafey** [comment]
Check the javascript console to see if there are any errors printed there.  Check to see if the image can be parsed by dicomParser here:
https://rawgit.com/chafey/dicomParser/master/examples/dumpWithDataDictionary/index.html
If that works, then you have a P10 file.  Next is to check the transfer syntax to see if it is one cornerstone supports, here is the list:
https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/docs/TransferSyntaxes.md

**Comment by sebastiankozub** [comment]
After few issues (CORS, Content-Type) finally I have displayed my own DCM file in your example browser. Good moment to include cornerstoneWADOImageLoader to my project ;)

**Comment by sebastiankozub** [comment]
Nice! Thanks for the help! Over 20MB DCM file loaded and presented in less than a second. Rendering looks better than in ClearCanvas in my opinion :)
Is there in cornerstonea ny function to load images with some kid of bulk method. For example load series of images into set of <div id="imgNN"></div> and than just make some kind of carousel with jquery with those <div>s?

**Comment by chafey** [comment]
There is no batch load mechanism in cornerstone, but it should be simple to implement yourself - just iterate over each imageId and call loadImage() on it.  There is also a stack prefetcher in cornerstoneTools that you may want to look at.

**Comment by chafey** [comment]
I think this issue is resolved - can you please close?

**Comment by sebastiankozub** [comment]
Thanks for the help...

**Comment by aksg87** [comment]
Hello all, 

Is there a simplified loader that can load  DICOM P10 without using the cornerstoneWADOImageLoader or is using this loader best?

**Comment by chafey** [comment]
I am aware of no other image loader for DICOM, why don't you want to use
cornerstoneWADOImageLoader?

**Comment by aksg87** [comment]
I thought it might be helpful to understand how cornerstone is handling image rendering, keeping all the DICOM files on my local machine. But I'll just go ahead and use cornerstoneWADOImageLoader. I local loader has a pretty limited use case. Thanks for your quickly reply! :-)

Unrelated -- but was curious how Cornerstone speed of rending images compares with DWV? Thanks again.

**Comment by chafey** [comment]
Cornerstone is superior in every way :)

**Comment by aksg87** [comment]
Yes that's what I thought :). I am creating a dynamic application with heavy use of annotations. I will likely want to create my own annotation object that interacts with cornerstone. 

Is this the best reference on best practices for annotating with cornerstone: https://github.com/cornerstonejs/cornerstoneTools/tree/master/examples/annotation

Thanks!

**Comment by Honey-hoo** [comment]
How to use dicomParse to parse the correct pixelData information 
This way can't get x7fe00010's pixelData,
`   
      
      var dataSet = dicomParser.parseDicom(byteArray);

      var imageObj = {};

      imageObj.windowCenter = dataSet.string('x00281050');

      imageObj.windowWidth = dataSet.string('x00281051');

      imageObj.accessionNumber = dataSet.string('x00080050');

      imageObj.acquisitionTime = dataSet.string('x00080032');

      imageObj.bitsAllocated = dataSet.string('x00280100');

      imageObj.highBit = dataSet.string('x00280102');

      imageObj.instanceNumber = dataSet.string('x00200013');

      imageObj.institutionName = dataSet.string('x00080080');

      imageObj.patientAge = dataSet.string('x00101010');

      imageObj.patientID = dataSet.string('x00100020');

      imageObj.patientName = dataSet.string('x00100010');

      imageObj.patientSex = dataSet.string('x00100040');

      imageObj.pixelRepresentation = dataSet.string('x00280103');

      imageObj.seriesDescription = dataSet.string('x0008103e');

      imageObj.seriesNumber = dataSet.string('x00200011');

      imageObj.sliceLocation = dataSet.string('x00201041');

      imageObj.sliceThickness` = dataSet.string('x00180050');

      imageObj.stationName = dataSet.string('x00081010');

       return imageObj;
`

**Comment by aamirswat** [comment]
hi i am facing error on header.php
