### ISSUE TITLE
Slow windowing

### ISSUE THREAD

**Issue by EmanHosny87** [chafey/cornerstone#29]
Hi Charey,
 
I am trying to use cornerstone in my project, when using CT/PET images with dimension 128x128 the change in window width and window level are slower than 512x512 !!This issue is simulated when using the HTLM5 viewer from iPhone.

Any ideas why this problem occurred also is there any way to correct this behavior ?

Thanks for your support :)

**Comment by chafey** [comment]
PET images often have a wider dynamic range than CT.  The wider the dynamic range, the more time it takes to generate the LUT during ww/wc adjustments.  There is work being done on a WebGL renderer which may help - stay tuned.

**Comment by EmanHosny87** [comment]
After re sizing the CT image into 256x256 in the server side and rendering it in the client side it is very slower than when it's retrieved 512x512 size ?
The loading of images is very faster when the size of image is 256 but windowing is very slow !
Any explanation ?!

**Comment by chafey** [comment]
I don't understand what your issue is - can you provide more information?

**Comment by chafey** [comment]
Any more information on this?  Will close if no response in the next 7 days.  Thanks

**Comment by chafey** [comment]
No response - closing
