### ISSUE TITLE
Non-square images are broken (shearing problem)

### ISSUE THREAD

**Issue by dblezek** [chafey/cornerstone#31]
Modified the [custom image loader](https://rawgit.com/chafey/cornerstone/master/example/imageloader/index.html) example to create a non-square image (256x200).  Got a broken rendering:

![broken image rendering](https://cloud.githubusercontent.com/assets/76340/9960028/b5dff566-5ddd-11e5-8963-df56dfeaf79f.png)

Got a bit lost in the source code, or would have submitted a pull request.  Any pointers helpful!

Broken code fragment (modified from the example, but intended to display NIfTI images):

```
        rows = 256;
        columns = 200;
        var width = rows;
        var height = columns;

        var numPixels = width * height;
        var pixelData = new Uint16Array(numPixels);
        var index = 0;
        var rnd = Math.round(Math.random() * 255);
        for (var y = 0; y < height; y++) {
          for (var x = 0; x < width; x++) {
            pixelData[index] = (x + rnd) % 256;
            index++;
          }
        }
```

**Comment by chafey** [comment]
Looks like you have rows and columns swapped

**Comment by dblezek** [comment]
![sigh](http://phandroid.s3.amazonaws.com/wp-content/uploads/2015/07/Picard-Facepalm.jpg)

@chafey thanks for the help, worked perfectly!
