### ISSUE TITLE
Publish cornerstone to npm

### ISSUE THREAD

**Issue by cancan101** [chafey/cornerstone#34]
It appears that currently Bower can be used to install cornerstone but cornerstone is not published to the `npm` repository.

**Comment by chafey** [comment]
In version 2.0 of cornerstone I am thinking we go full ES6 modules + NPM for deployment only.  Adding support for NPM deployment right now is an option, but I would like some help with it.  Drop me an email if this is something you are willing to help with (or anyone else out there)

**Comment by taion** [comment]
I'm not aware of any packages that distribute only an ES6 module build. It's not uncommon to use ES6 modules (and ES6 more broadly) for source, but typically we transpile distributed releases to ES5 before publishing to npm. Optionally, we provide an ES6 module build for rollup and webpack 2 users to get the benefits of tree shaking.

This is how we currently distribute React Router and Redux, if you're familiar with the React ecosystem at all.

**Comment by chafey** [comment]
@taion agreed - I really like the way moment.js has approached this:

https://github.com/moment/moment/

**Comment by taion** [comment]
Sure – the one comment I'd add is that it's atypical to include built artifacts in source control, unless you're also distributing to Bower. More common to only have them in your npm package, and direct users at e.g. npmcdn if they need to include your bundle via a `<script>` tag.

**Comment by chafey** [comment]
bower seemed to be the best way to distribute client side JS when I started the project.  Now that bower has been discontinued, I think I will eventually drop it and switch to NPM exclusively and follow its conventions properly

**Comment by cancan101** [comment]
Any chance of seeing this in an upcoming release?

**Comment by chafey** [comment]
Right now I am thinking the 2.0 release which has no target release date.  If someone wants to do the work I would be willing to work with them to get it done earlier

**Comment by swederik** [comment]
Done!
