### ISSUE TITLE
Handling invalid images

### ISSUE THREAD

**Issue by novocainer** [chafey/cornerstone#42]
What would be the best way to handle invalid images when using cornerstonetools.stackSroll? 

I've had a problem whereby an invalid image causes an exception to be thrown, but there seems to be no way of recovering from it. As far as I can see the only way to do it would be to pre-validate the images but even in that case, how should errors best be handled?

**Comment by chafey** [comment]
Check out cornerstoneTools.loadHandlerManager to register callbacks to take action when things like this go wrong.  Our viewer simply displays an error to the user when this happens.

https://github.com/chafey/cornerstoneTools/blob/master/src/stateManagement/loadHandlerManager.js

**Comment by novocainer** [comment]
Thanks for your prompt response! I'm looking into it.

**Comment by chafey** [comment]
Please close this issue if it is resolved.  Thanks

**Comment by novocainer** [comment]
Thanks.
