### ISSUE TITLE
My Angular app cannot retrieve external Orthanc .dcm resources if called straight from the browser

### ISSUE THREAD

**Issue by mcajhill** [chafey/cornerstone#44]
In order to retrieve Orthanc resources in my Angular webapp, two methods are employed. 
  - The front end makes a call to the server in order to request textual information from an Orthanc instance regarding a study or series 
  - The front end makes a call directly to an Orthanc server instance in order to request .dcm files to use with a JS web viewer (using Cornerstone) 

The first method works perfectly well and is used to list summary information about studies/series stored in Orthanc. However, the second method (used to pull down the .dcm images themselves for use with the Web Viewer) is proving to be problematic. 

This problem is related to cross origin resource sharing, and the use of a third party library called Cornerstone in order to retrieve the .dcm files. 

The framework we use for our web layer is Angular, yet Cornerstone uses JQuery in order to make the AJAX requests for resources. Therefore, I can’t manually add the access-control-allow-origin header on the request to implicitly trust the Orthanc server (i.e. via an Angular module .config setup) because we don't make the calls using the Angular $http service. 

It seems that this problem is related to how Cornerstone relies on the principle of any DICOM files being transported through a server layer as a middle tier in any communication between Orthanc and a front end UI. However, we don’t want our server to grind to a halt by transporting large image files through it. 

How to approach or bypass this when using Cornerstone? 

Thanks, 
Josh

**Comment by chafey** [comment]
See my response here: 
https://groups.google.com/forum/#!topic/orthanc-users/-a_qgYFzddU

**Comment by chafey** [comment]
Can you please close if this addressed your issue?

**Comment by mcajhill** [comment]
Hi sorry for the lateness of this.

Thanks for all the input, much appreciated. I'm going to close this issue now.
