### ISSUE TITLE
Update demo code

### ISSUE THREAD

**Issue by 73sl4** [chafey/cornerstone#46]
Hi,

I went through CornerStone library and it's really helpful for the project I am doing.
I was using your demo code to get it started. After which I replaced the older library with newer one and it  broke it.
I am getting error
```Uncaught TypeError: enabledElement.image.render is not a function```

I was hoping if you could update the demo code or help me resolve this issue.

Thanks

**Comment by chafey** [comment]
My guess is you didn't upgrade the other libraries to the matching versions.  If you use bower, it will do this automatically for you.  If not, check bower.json and make sure you have the right versions of the other libraries (my guess is you need to update cornerstoneWADOImageLoader)

**Comment by chafey** [comment]
OH and I will be updating the demo app to the latest libraries soon - just been busy

**Comment by 73sl4** [comment]
@chafey I'll upgrade all the other libraries to latest version.
Thanks :)

**Comment by chafey** [comment]
Closing
