### ISSUE TITLE
Demo program needing huge browser window

### ISSUE THREAD

**Issue by brianhannamn** [chafey/cornerstone#48]
Hi - love the project! Very useful.

With the demo program, I seem to get some strange behavior with smaller windows and / or large number of series within a study.
- the studies list continues to show at the top of the page instead of clearing and showing only the tab.
- the control buttons fold over and appear vertically at the left of the image window
- making the browser full screen or regular window can toggle display of the image (as if too big to show)

Going back to the studies list and clicking the same study also creates a new tab instead of revisiting the tab already created.

Small issues with a great project - keep up the good work!

Cheers, Brian Hanna CMRR

**Comment by chafey** [comment]
Hi Brian, glad you find cornerstone useful.  The cornerstoneDemo project is a demo of cornerstone - it is not complete and has some bugs like you are finding.  If you are looking for a more robust/functional viewer, please take a look at the OHIF Viewer here:

https://github.com/OHIF/Viewers

I don't generally fix issues like this in the cornerstoneDemo, but if you happen to fix them, feel free to submit a PR

**Comment by brianhannamn** [comment]
Thank you Chris,  I will check that out.  Cheers Brian
