### ISSUE TITLE
Ruler on the Image

### ISSUE THREAD

**Issue by MAhmedSaeed** [chafey/cornerstone#49]
Is cornerstone tools draw ruler porpotion with the image zooming?

**Comment by chafey** [comment]
Yes, all tools use image coordinates and are therefore independent of the zoom

**Comment by MAhmedSaeed** [comment]
fine, How can i draw ruler like the attached image
![rulers](https://cloud.githubusercontent.com/assets/17268318/13459770/78bda2b8-e07e-11e5-9cba-06997214d3dd.jpg)

**Comment by swederik** [comment]
We have a ruler tool here: http://lesiontracker.ohif.org/

The code is here: https://github.com/OHIF/Viewers/blob/master/Packages/lesiontracker/client/compatibility/scaleOverlayTool.js

We haven't put it into Cornerstone Tools yet, but it is on our backlog.

Please post future tool-related issues there instead: https://github.com/chafey/cornerstoneTools

Questions like this should be posted on the Cornerstone google group: https://groups.google.com/forum/#!forum/cornerstone-platform

**Comment by MAhmedSaeed** [comment]
ok thank you

**Comment by swederik** [comment]
No problem, I'll close this then.
