### ISSUE TITLE
Add support for bitmap "layers" with transparency support

### ISSUE THREAD

**Issue by chafey** [chafey/cornerstone#50]
So we can implement fusion and segmentation masks natively in the rendering pipeline

**Comment by mko** [comment]
A couple of quick notes:

- It would be useful to be able to select multiple imageIds, preferably with embedded image registration references (i.e. RCS in DICOM Registration References) or discrete image registration definitions within Cornerstone, as the different layers. I've worked around the issue already without layers by doing CSS-based overlays, but it certainly doesn't provide the same effect as actual layering would.
- When layering, it would be good to have the ability to transform the layers via a simple API once created as well (i.e. storing original layer references for effectively non-destructive layering). A good use case would be creating an image registration system where you might want to layer two or more imaging modalities on top of each other to align them, but the application needs to be able to modify the two layers independently.

**Comment by chafey** [comment]
OK had some time to think about this a bit.  Making this as flexible as it needs to be is going to increase the complexity of cornerstone core which is something I want to avoid.  I am starting to think we should make the rendering pipeline pluggable and move this whole thing into another library.

I don't see any issue with doing transformations on the layers.  I am thinking we will keep the design "immediate mode" rather than "retained mode".  So if you adjust the transformation, you would have to trigger an invalidation as well.  

DICOM SEG objects have a concept called "FRACTIONAL" which contain a value per point between 0-255 that would probably map transparency or a color table.  Still researching this one to make sure I understand it fully.

**Comment by swederik** [comment]
Here is a live demo of what I have so far:

https://rawgit.com/swederik/cornerstone/composition/example/layers/index.html

It needs a ton of work, obviously.

**Comment by swederik** [comment]
This is finally available. Example here: https://rawgit.com/chafey/cornerstone/master/example/layers/index.html
