### ISSUE TITLE
Dicom patient ids with slash

### ISSUE THREAD

**Issue by brianhannamn** [chafey/cornerstone#53]
Had a problem with some DICOM patient ids containing slashes. cornerstoneDemo.js uses the patient id as an id for an anchor tag for the new tab, but slashes give jQuery problems. In the studyRowElement click function, I added

      var patientIdnoslash = study.patientId;
      patientIdnoslash = patientIdnoslash.split('/').join('-');

And changed:

      // Add new tab for this study and switch to it
      var studyTab = '<li><a href="#x' + patientIdnoslash + '" data-toggle="tab">' + study.patientName + '</a></li>';
      ...
      studyViewerCopy.attr("id", 'x' + patientIdnoslash);

And then patient ids with slashes are no problem. 

Cheers, Brian

**Comment by pangyre** [comment]
This seems like a unnecessary hack likely to bite at some point in the chain. Wouldn’t it be better to URI escape the arguments. And submit a patch to jQuery if they are parsing #args without proper unescaping.

**Comment by chafey** [comment]
Closing - this issue is related to cornerstoneDemo and not cornerstone itself
