### ISSUE TITLE
Local image in brower

### ISSUE THREAD

**Issue by For-me** [chafey/cornerstone#54]
Hi,Thx for create this library.I meet some questions.And hope u can give me some methods to solve it.
In your examples,local image is became base64, If i just have imgae format like png or jpg,How can i do it(Because i have more images,If all is converted to Base64, this is a very cost performance.)。
Wish u replay!

**Comment by chafey** [comment]
Hi - See my answer to this question on the forum: 

https://groups.google.com/forum/#!searchin/cornerstone-platform/base64/cornerstone-platform/GSjk38DWkzs/MlSfvhKRTX0J

**Comment by For-me** [comment]
Maybe https://github.com/chafey/cornerstoneWebImageLoader can resolve it?  But ww/wl is not surport?

**Comment by chafey** [comment]
cornerstoneWebImageLoader does support loading standard PNG and JPEG images via HTTP, it does not have support for loading from the local file system although this could be added in the same way cornerstoneWADOImageLoader does it for dicomfile.  Cornerstone supports WW/WL for all image types including PNG and JPEG.  Note that you will want to do WW/WC on the original images, not on rendered JPEG and PNG versions of them

**Comment by For-me** [comment]
OK.Thanks for replay.
