### ISSUE TITLE
Study thumbnail show the progress when loading

### ISSUE THREAD

**Issue by danielaromeo** [chafey/cornerstone#55]
I've used the example JS Dicom Viewer to have my own viewer and I added a loader to the thumbnails bar on the left which is shown till the thumbs are loaded. I have just one question: is it possible to show the progress when loading the thumbnail? I mean with percentages, for instance 10%, 35% etc. till 100%.

Thank you!

**Comment by chafey** [comment]
Yes cornerstone defines how an image loader would do this here:

https://github.com/chafey/cornerstone/wiki/CornerstoneImageLoadProgress-Event

And this is implemented by cornerstoneWADOImageLoader here:

https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/src/xhrRequest.js#L36

which depends on XHR lengthComputable, which depends on the server providing specific HTTP headers and possibly the web browser implementation of XHR

**Comment by bhanuhiteshi** [comment]
**Updated cornerstoneWADOImageLoader Implementation Link:**

[https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/internal/xhrRequest.js#L80](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/internal/xhrRequest.js#L80)
