### ISSUE TITLE
Problem with a DICOM image

### ISSUE THREAD

**Issue by danielaromeo** [chafey/cornerstone#57]
I'm developing a custom DICOM viewer using your demo as a base and I'm having issues with a particular set of images. Attached you can find one of them.
I tried to upload that image here: http://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html and it worked. So I have added the following js codec libraries (two of them are used in your page):
- jpx.js
- libCharLS.js
- libopenjpeg.js

but the image still doesn't show. All I can see is a white rectangle (please see the attached screenshot).
Do you have any advice to understand what's going on and fix my issue?

Thank you!
Daniela

[issue.zip](https://github.com/chafey/cornerstone/files/300979/issue.zip)

**Comment by chafey** [comment]
The image is JPEG Lossless (.70) which doesn't currently require a codec.  Are you using the latest cornerstoneWADOImageLoader release?

**Comment by danielaromeo** [comment]
Hi chafey, thank you for your prompt reply.

I was using v0.7.0, not the latest .
Now I have tried with the latest one (v0.13.3) and I cannot see anything, the white rectangle disappeared and the image is not shown at all.

**Comment by chafey** [comment]
you may need to update all the other libraries too - cornerstone, cornerstoneTools, dicomParser, etc

**Comment by danielaromeo** [comment]
Ok, I'll try and let you know! Thank you again!

**Comment by danielaromeo** [comment]
Hi chafey,
upgrading all the libraries to the latest version worked with that image, but I have another image that cannot be opened. I know it is compressed, so maybe the issue is there. You can find it attached to this message, I hope you'll be able to help me.

[IDEFAULT.zip](https://github.com/chafey/cornerstone/files/306945/IDEFAULT.zip)
Thank you!

**Comment by malaterre** [comment]
Best example for [JPEG Image Compression note](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_8.2.html#para_4bcb841e-c6bf-4e26-82a5-3fad3c942da0) ! You should share it on DICOM newsgroup.

**Comment by danielaromeo** [comment]
Hi malaterre, thank you for your reply. Is this the DICOM newsgroup? https://groups.google.com/forum/#!forum/comp.protocols.dicom .

**Comment by malaterre** [comment]
@danielaromeo yes ! Pay attention that this image is 'made-up' it cannot possibly be coming out of a real world PACS system. But clearly a robust library should handle that beast.

**Comment by danielaromeo** [comment]
Thank you very much malaterre! Weasis Java Viewer opens it, but it seems it's the only one software which can in fact. 

Thank you everyone for the help!

**Comment by malaterre** [comment]
I did not meant for you to close this bug report...

**Comment by danielaromeo** [comment]
Sorry, I thought it was solved as the image is a made-up one (my team did it) and that is the problem, not your viewer.

**Comment by chafey** [comment]
This image is missing the rows and columns attributes which are required by DICOM.

**Comment by danielaromeo** [comment]
Thank you chafey, this is a precious hint!
