### ISSUE TITLE
[ImageCache] cachedImages had no property sharedCacheKey

### ISSUE THREAD

**Issue by ghetolay** [chafey/cornerstone#58]
I don't use imageCache and so didn't really looked at how it works. But I'm transcoding cornerstone into typescript (preparation phase for an angular 2 version) and it's complaining about ```cachedImages``` not having a ```sharedCacheKey``` property.

It's inside ```removeImagePromise()``` and I think it's right since ```cacheImages``` is an Array and even if we can add custom properties to an Array I didn't find such assignation. Also there is a local var named ```cacheImage``` so I guess it's meant to be ```cacheImage.sharedCacheKey``` instead of ```cacheImages.sharedCacheKey ```

**Comment by chafey** [comment]
Thanks for reporting this - will be fixed in version 0.10.0
