### ISSUE TITLE
[setToPixelCoordinateSystem] context.setTransformhas takes only 6 arguments

### ISSUE THREAD

**Issue by ghetolay** [chafey/cornerstone#59]
Again from typescript a really minor error (which cause no trouble) on ```setToPixelCoordinateSystem()``` : 

```
context.setTransform(transform.m[0],transform.m[1],transform.m[2],transform.m[3],transform.m[4],transform.m[5], transform.m[6]);
```

```CanvasRenderingContext2D.setTransform()``` only takes 6 arguments and ```Transform.m``` also is an Array of just 6 numbers.
So ```transform.m[6]``` is undefined but luckily ```setTransform()``` do not use that argument :) 

Should be : 

```
context.setTransform(transform.m[0],transform.m[1],transform.m[2],transform.m[3],transform.m[4],transform.m[5]);
```

P.S.: creating a PR (meaning new branch on my fork sync with this repo + new branch to hold changes + commit + PR) seems too much trouble for such small and minor bug.

**Comment by chafey** [comment]
Thanks for reporting this, will be fixed in 0.10.0
