### ISSUE TITLE
[getDefaultViewport] image has no property modalityLUT nor voiLUT

### ISSUE THREAD

**Issue by ghetolay** [chafey/cornerstone#61]
On getDefaultViewport() we are coping modalityLUT and voiLUT properties of image into the new created viewport like so : 

``` javascript
 return {
    scale : 1,
    translation : {
        x : 0,
        y : 0
    },
    voi : {
        windowWidth: image.windowWidth,
        windowCenter: image.windowCenter,
    },
    invert: image.invert,
    pixelReplication: false,
    rotation: 0,
    hflip: false,
    vflip: false,
    modalityLUT: image.modalityLUT,
    voiLUT: image.voiLUT
};
```

Except we are never setting `modalityLUT` nor `voiLUT` on the image object anywhere on the library. So theses properties will most likely be `undefined`.
But on `renderGrayscaleImage` we are doing :

``` javascript
  image.lut.voiLUT = viewport.voiLUT;
  image.lut.modalityLUT = viewport.modalityLUT;
```

So we should either set `modalityLUT` and `voiLUT` into the image object or into the lut object (which is in fact an Int16Array).

**Comment by chafey** [comment]
modalityLUT and voiLUT are set on the image object in cornerstoneWADOImageLoader - does that explain things?

**Comment by ghetolay** [comment]
Ok this explain some things but taking for example voiLUT  we have 
- ```image.voiLUT``` which is some kind of default lut.
- ```viewport.lut```    which is the lut we want to apply during a display
- ```image.lut.voiLUT``` which is a cache of the last lut used with this image on any enabledElement

While I can understand the first 2, the last one seems weird. In fact the whole ```image.lut``` property seems weird  because it's a rendering property not related to the image. I think image should be an immutable object.

So that issue is more a design concern than a code issue.

**Comment by swederik** [comment]
image.lut has been changed to image.cachedLut so this should be more clear now.
