### ISSUE TITLE
Is XA (X-Ray Angiography) series supported?

### ISSUE THREAD

**Issue by ftaurino** [chafey/cornerstone#64]
Hi all,

is cornerstone (or related libraries) able to render a XA series?

Thank you,

Francesco

**Comment by chafey** [comment]
Yes

**Comment by chafey** [comment]
Cornerstone displays all known DICOM types - you can test this out by opening the file using this example:
http://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

**Comment by ftaurino** [comment]
thank you!

**Comment by mmeppiel** [comment]
Hi all,

I seem to be having some issues using cornerstone in a Bootstrap modal. Is
this supported? I'm using the WADO image loader and it appears that the
height and width are being drawn as 0px inside the modal. The same code
outside the modal works perfectly. Any help?

Thanks,
Matthew

**Comment by ftaurino** [comment]
hi,

now my cornerstone demo open almost all dicom files, except XA.
I've a XA angiogram from osirix (http://www.osirix-viewer.com/datasets/DATA/GRUSELAMBIX.zip)
with this json used to load the study:
......
   "instanceList" : [
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-0001.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-0002.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-0003.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-0004.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage//M201606200025/DICOM/8/IM-0001-0005.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-0006.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-0007.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-0008.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-0009.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-00010.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-00011.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-00012.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage/M201606200025/DICOM/8/IM-0001-00013.dcm"},
                {"imageId" : "dicomweb:/studies/getdicomimage//M201606200025/DICOM/8/IM-0001-00014.dcm"}
            ]
......
the json imageId urls are the same of working studies.

the web page load the json and the dcm files, but the study shows a strange image
with a js error in console: "Uncaught dicomParser.readFixedString: attempt to read past end of buffer".

![screenshot from 2016-06-25 18 11 21](https://cloud.githubusercontent.com/assets/7099799/16357791/591dc3e8-3b00-11e6-9b65-a9ec6fa66488.png)

**Comment by chafey** [comment]
These images load fine using the latest version of cornerstoneWADOImageLoader:

http://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

Try upgrading to the latest versions of the libraries and using the OpenJPEG2000 codec
