### ISSUE TITLE
Sometimes the WL tool is slow

### ISSUE THREAD

**Issue by gokhandilek** [chafey/cornerstone#66]
I was wondering why sometimes the WW/WC tool is really slow.
For example, the WW/WL is set to 319/224, I click the image and move the cursor, it is extremely slow(the render time is about 500ms). It only moves up 1 unit so 319/224 becomes 320/225 for example and it takes 500ms to render this.

All other tools seem be working(not frozen) and the browser is not frozen as well.
(Invert tool around 30ms, elliptical and rectangular tool around 40ms, zoom in-out around 5ms, pan around 3 ms).

I have another study open on another tab which the render time is about 60ms for WW/WC tool.
Is there a particular reason why this particular study is slow. Any way to track this or check?
Thank you.
Versions I use:
cornerstoneTools - v0.7.2 - 2015-09-07
cornerstoneWebImageLoader - v0.5.2 - 2015-09-06
dicom-parser - v1.1.5 - 2015-08-12

**Comment by Ethoxyethaan** [comment]
High resolution images require more CPU to window level in cornerstone. (CR & MG vs CT & MR)
Original images have their correct pallet applied and are then scaled to the desired display size.
the TS could possibly also play a role for decoding the pixels each time a new window level is set.

**Comment by gokhandilek** [comment]
I totally understand if the images have higher resolution which will require more CPU power.
But considering these two different studies having the same resolution, I do not understand why  it is slow in one image and the other image renders just fine.

**Comment by chafey** [comment]
The factors that impact WW/WC performance:
1) Resolution
2) Dynamic Range of image  
3) Presence of Modality LUT
4) Presence of VOI LUT

**Comment by gokhandilek** [comment]
Thank you chafey.
1- What is the recommended resolution? 
Would increasing Chrome's dedicated memory to cornerstone canvas improve the performance?

**Comment by chafey** [comment]
By resolution I am referring to the resolution of the image.  Increasing chromes memory for canvas will not help.  There is an experimental WebGL renderer that you can try out

**Comment by chafey** [comment]
Did this answer your question?  If so please close

**Comment by gokhandilek** [comment]
I am sorry. I am still testing this. I will reply once I find out more.
Thank you.

**Comment by gokhandilek** [comment]
ok.
My problem was loading the object in jpeg format. Somehow cornerstone does not render this format very well.
As soon as I switched to dicom, it is really fast!
