### ISSUE TITLE
dev branch bower version

### ISSUE THREAD

**Issue by lambacini** [chafey/cornerstone#70]
incorrect cornerstone bower version.
CornerstoneTools (dev) and WadoImageloader (dev) need 0.10.0  but dev branch verson 0.9.0

try install cornerstoneTools#dev

bower cornerstone#~0.10.0      ENORESTARGET No tag found that was able to satisfy ~0.10.0

**Comment by chafey** [comment]
The /dev branch is for work currently in development (not yet released) and is releasing the other libraries that are not yet released.  You will have to manually copy them down (without bower) to work with the dev branch

**Comment by lambacini** [comment]
I understand but no need release 0.10.0 version, if change bower.json in 
cornerstoneTools#dev and 
cornerstoneWADOImageLoader#dev    "dependencies": { "cornerstone": "dev", maybe solve the problem.
sorry my bad english.
