### ISSUE TITLE
issue with image download 

### ISSUE THREAD

**Issue by AyeshaAzeez** [chafey/cornerstone#71]
I downloaded the cornerstoneDemo source code from GitHub. I am trying to download an image (jpegas well as dcm) from the application. I understand that the image is loaded from "dicomweb://cornerstonetech.org/images/ClearCanvas/" 
I am trying to download an image when it is loaded on to the viewer dynamically (as in, the current image ID has to be appended to the URL "dicomweb://cornerstonetech.org/images/ClearCanvas/" ).
Is it possible to download the image from cornerstone? If so, how?

**Comment by swederik** [comment]
Cornerstone does not currently provide any method for downloading the displayed image.

Since you have the imageId, though, you should be able to replace the 'dicomweb' prefix with something like 'http' and then use that link to download the file.

Hope that helps!
