### ISSUE TITLE
Viewing studies from local system

### ISSUE THREAD

**Issue by gokhandilek** [chafey/cornerstone#73]
<img width="1367" alt="screen shot 2016-09-17 at 11 52 58 pm" src="https://cloud.githubusercontent.com/assets/10161605/18609320/f3c726c8-7d31-11e6-9428-c7a675e66d6e.png">
I am just testing out the [cornerstone demo](http://chafey.github.io/cornerstoneDemo/) to load local DICOM files.

I am having issues (all black canvas) when viewing. Looking at the chrome developer console, I can see the files loading but the size of the files are 0B?

Could you please let me know if cornerstonewado loader.js supports file:// protocol?

If not, what is your suggestion to load local DICOM files to cornerstone dicom?

PS: I am using chromium with --allow-file-access-from-files flag.

Thank you.

**Comment by gokhandilek** [comment]
I managed to load the files via local web server.

**Comment by lambacini** [comment]
WadoImageLoader support " dicomfile: " schema..
you can use "cornerstoneWADOImageLoader.wadouri.fileManager.add".
function return "dicomfile:index" loader schema.


```
//items is drag or '<input ="file" webkitdirectory ' source 
var items = e.originalEvent.dataTransfer.items;
var files = [];

for (var i = 0; i < items.length; i++) {
    var entry = items[i].webkitGetAsEntry();
    traverse(entry);
}

function traverse(entry, path) {
    path = path || "";
    if (entry.isFile) {
        // Get file 
        entry.file(function (file) {
            files.push(file);
        });
    } else if (entry.isDirectory) {
        // Get files in folder 
        var dirReader = entry.createReader();

        dirReader.readEntries(function (entries) {
            for (var i = 0; i < entries.length; i++) {
                traverse(entries[i], path + entry.name + "/");
            }
        });
    }
}

$.each(files, function (key, file) {
    var fileid = cornerstoneWADOImageLoader.wadouri.fileManager.add(file);
    dicom.loadAndCacheImage(fileid)
        .then(function (image) {

        });
});
```

**Comment by j0nj0n** [comment]
Hello,
I am struggling with the same problem.
Where would you place this function traverse?
Was your file format for dicom also with the json.
