### ISSUE TITLE
Structured Reports

### ISSUE THREAD

**Issue by danielaromeo** [chafey/cornerstone#74]
I have created a DICOM viewer using your libraries, but I'm not able to open a Structured Report file (the extension is always .dcm).
Is there any library I should add to see the report in the viewer?

Thank you!

**Comment by fedorov** [comment]
What kind of SR are you trying to open? Do you know what SR template the document you are trying to open follows?

**Comment by danielaromeo** [comment]
Hi, thank you for your reply. 
No, I don't know what SR template the document follows. I only know that it's a Structured Report. 
I attach the file to this message, I hope it can be useful.
Thanks!
[sr.zip](https://github.com/chafey/cornerstone/files/525011/sr.zip)

**Comment by fedorov** [comment]
Please confirm you are not sharing patient info in the sample dataset you shared! If this is the case, you might want to edit your post and remove the link!

Looking at the report, it appears to be a Basic Text SR, there is nothing relevant to display in the cornerstone viewer - it does not reference any images.

As an aside, you can use [Atom editor ](https://atom.io/) with [dicom-dump plugin](https://atom.io/packages/dicom-dump) that wraps [dcmtk](http://dcmtk.org/) dsrdump tool to quickly examine SR files. This is what I did to quickly look at the file you shared.

**Comment by pangyre** [comment]
Whoah! Please, Can that zip be removed instantly!? It's apparently got PHI in it.

**Comment by fedorov** [comment]
Perhaps repo owners have the rights to edit that post? I don't.

**Comment by danielaromeo** [comment]
I removed it, but the person who sent me told me it wasn't a real one, sorry. I'll ask for another one.

**Comment by danielaromeo** [comment]
Thank you for the tips about the plugins, I'll try them :)

**Comment by yoni-bme** [comment]
How can I add structured report on orthanc

**Comment by No-Dream-No-Life** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，邮件我已收到，我将在看到后第一时间给您回复。

**Comment by yoni-bme** [comment]
What
