### ISSUE TITLE
Some images not opening

### ISSUE THREAD

**Issue by danielaromeo** [chafey/cornerstone#75]
Hello, I have an issue with the images I attach here. 
I tried also to load them here: http://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html, but the response is "unknown pixel format".
Could you please help?
Thank you
[images.zip](https://github.com/chafey/cornerstone/files/527340/images.zip)

**Comment by fedorov** [comment]
one of them is BasicTextSRStorage - nothing relevant to show in the image viewer

**Comment by danielaromeo** [comment]
Ah ok, is there a way to skip those images and not showing them in the viewer? I'm using a json to receive the images as in your demo, so I need to skip those images after reading the json

**Comment by chafey** [comment]
Correct - one is SR and the other is PR, neither of which are "Images" but
more "information about images".  Would be great to add support for these
in cornerstone but nobody has worked on either yet

**Comment by chafey** [comment]
Yes, filter them out when creating the JSON or client side....

**Comment by danielaromeo** [comment]
Thank you! Yes, it would be great to add the support for those kind of files.
So I can do it just by checking the modality (SR,PR) or should I check something else?

**Comment by swederik** [comment]
You can check the sopClassUid against a list of image types.

We do that in the OHIF Viewer here:

https://github.com/OHIF/Viewers/blob/c9236b96f99aabdc9a793f1584d5051d0ed99f1b/Packages/ohif-viewerbase/client/lib/isImage.js#L8
https://github.com/OHIF/Viewers/blob/c9236b96f99aabdc9a793f1584d5051d0ed99f1b/Packages/ohif-viewerbase/client/lib/sopClassDictionary.js

Hope that helps!
