### ISSUE TITLE
Multiple viewports rendering has race condition issues on Safari 10 

### ISSUE THREAD

**Issue by hroenick** [chafey/cornerstone#78]
Hi guys.

I have experimented some rendering issues while working with multiple viewports (essentially a viewport is related to a HTML 5 canvas) on Safari 10. This issue does not reproduces on earlier versions of Safari and on Firefox or Chrome. Apparently on this new version of Safari some change happened related to canvas rendering.

What I realised is that cornerstone rendering method share some rendering variables along with others viewports and this started to be an issue on Safari 10. The variables I am referencing are:
- on grayscaleRenderer:
  -- var grayscaleRenderCanvas
  -- var grayscaleRenderCanvasContext;
  -- var grayscaleRenderCanvasData;
  -- var lastRenderedImageId;
  -- var lastRenderedViewport;
- on colorRendered:
  -- var colorRenderCanvas
  -- var colorRenderCanvasContext;
  -- var colorRenderCanvasData;
  -- var lastRenderedImageId;
  -- var lastRenderedViewport;

The problem is that if I have 2 canvas (A and B) and request to draw image 1 on canvas A and image 2 on canvas B, its possible that both canvas have the image 2 rendered on them.

I built a simple fix proposed on the pull request  #77
I'm not sure if this fix is the most appropriate strategy.

Hope that I could help.

**Comment by pasha123456** [comment]
Hi guys,
My name is Pavel and I am new here - so please be forgiving if I am not asking in the right place :-)
I also encountered this issue - not with Safari - but with JavaFx WebView.
Any progress with this issue? Was the referenced pull request #77 merged / any ETA to release?
Thanks

**Comment by swederik** [comment]
Hi Hugo and Pavel,

I have merged #77 and so this issue is fixed now.

Thanks!
