### ISSUE TITLE
Consider using RequestAnimationFrame() to stack render calls.

### ISSUE THREAD

**Issue by jpambrun** [chafey/cornerstone#81]
Images are currently re-rendered multiple times between each displayed frame. This inefficient, especially for battery-driven devices.

![20170116165617](https://cloud.githubusercontent.com/assets/718384/22000346/a02b2890-dc0c-11e6-92b8-aacdc0797198.png)

RequestAnimationFrame() stacks render calls so that the render function is only called once per frame by the browser. However, we would need to implement some kind of manager to handle multiple viewports.

**Comment by jpambrun** [comment]
After some digging, I think this can be achieved easily by using cornerstone.invalidate(element) and calling drawInvalidated() from the (or as the) RequestAnimationFram callback once #82 is fixed.

**Comment by swederik** [comment]
We have now moved to RequestAnimationFrame so I'm going to close this.

Relevant commit was: https://github.com/chafey/cornerstone/commit/2d5f6a1db805be208d719097f16ef4ad5b47987b
