### ISSUE TITLE
WW/WC not working for CT dicom  color images  after mouse dragging    why?    fast drawing 

### ISSUE THREAD

**Issue by fashionmacker** [chafey/cornerstone#96]
Hello,
I am talking  about  getRenderCanvas(enabledElement, image, invalidated)  in cornerstone.js  
For color images we  have check  ww 255 and wc=128   in if clause    line:1712      why?  

İf our images set ww/wc 255/128   When we  did  ww/wc   active  screen be  dark 
and we set ww/wc 255/128 again  doesnt work image rendered 

Thaks for all things

**Comment by swederik** [comment]
Hi there,

Thanks for the report. This appears to have come from this commit:

https://github.com/chafey/cornerstone/commit/17b4b2bddf7dd20304031717e8a03c3e1fea675c

I will have to investigate what @chafey was fixing to figure out what has gone wrong here.

**Comment by swederik** [comment]
This turned out to be an issue in the Cornerstone WADO Image Loader. I have fixed it here: https://github.com/chafey/cornerstoneWADOImageLoader/commit/c5dc4b23d15764f6806a2dda44cf7c6d855e286a

Please update this library in your application and the problem should be resolved.

Hope that helps!
